'use strict';
const P=Physics,$=id=>document.getElementById(id);
const defs=[
 ['sum','Operações','Soma','x + y','z = x + y'],['subtract','Operações','Subtração','x - y','z = x − y'],['multiply','Operações','Multiplicação','x*y','z = x · y'],['divide','Operações','Divisão','x/y','z = x / y'],['power','Operações','Potência','x^n','z = xⁿ',{n:2}],['product','Operações','Produto com potências','x^a*y^b','z = xᵃ · yᵇ',{a:2,b:1}],['sumsquares','Operações','Soma dos quadrados','x^2+y^2','D² = x² + y²'],
 ['mean','Estatística','Média aritmética',null,'x̄ = Σxᵢ / n'],['deviation','Estatística','Desvio em relação à média',null,'dᵢ = xᵢ − x̄'],['absdeviation','Estatística','Desvio absoluto',null,'dᵢ = |xᵢ − x̄|'],['std','Estatística','Desvio padrão amostral',null,'s = √[Σ(xᵢ − x̄)² / (n − 1)]'],['sem','Estatística','Desvio padrão da média',null,'σx̄ = s / √n'],
 ['absolute','Erros','Erro absoluto','abs(x-r)','Eₐ = |x − xref|'],['relative','Erros','Erro relativo','abs(x-r)/abs(r)','Eᵣ = |x − xref| / |xref|'],['percent','Erros','Erro percentual','100*abs(x-r)/abs(r)','E% = 100 Eᵣ'],
 ['square','Linearização','Quadrado','x^2','y = x²'],['cube','Linearização','Cubo','x^3','y = x³'],['sqrt','Linearização','Raiz quadrada','sqrt(x)','y = √x'],['inverse','Linearização','Inverso','1/x','y = 1/x'],['ln','Linearização','Logaritmo natural','ln(x)','y = ln(x)'],['log10','Linearização','Logaritmo decimal','log10(x)','y = log₁₀(x)'],['custom','Personalizada','Fórmula personalizada','','Expressão → nova coluna']
];
let state={cols:[],rows:[],next:1},redo=[],prepared=null,cache=[],errors=[],dirty=false,lastStats=null,statMemo=new Map();
const nameOf=id=>state.cols.find(c=>c.id===id)?.name||id;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function guard(fn){return (...args)=>{try{return fn(...args);}catch(e){status(e.message,true);}};}
const fmt=v=>{if(v===null||v===undefined)return '';const d=Number($('digits').value);const s=$('format').value==='decimal'?v.toFixed(d):v.toPrecision(d);return s.replace('.',',');};
function validateName(name,except){if(!name.trim())throw Error('Dê um nome à coluna.');if(name.length>50||/[\[\]\r\n]/.test(name))throw Error('Nome muito longo ou com caracteres reservados.');if(['pi','π','e','sqrt','ln','log10','abs','exp','sin','cos'].includes(name))throw Error('Este nome é reservado para uma função ou constante.');if(state.cols.some(c=>c.id!==except&&c.name===name))throw Error('Já existe uma coluna com esse nome.');}
function newCol(name,unit=''){validateName(name);const c={id:'c'+state.next++,name,unit};state.cols.push(c);return c;}
function blank(){state={cols:[],rows:[],next:1};redo=[];lastStats=null;for(const name of ['d1','vd1','d2','vd2'])newCol(name,'mm');state.rows=Array.from({length:3},()=>({}));}
function hasData(){return state.cols.some(c=>c.calc)||state.rows.some(r=>Object.values(r).some(v=>String(v).trim()));}
function replaceAllowed(){return !hasData()||confirm('Substituir a tabela atual? Salve ou exporte os dados antes de continuar.');}
function statFor(id,values){if(statMemo.has(id))return statMemo.get(id);const xs=[];for(let i=0;i<state.rows.length;i++){const original=state.cols.find(c=>c.id===id);if(!original?.calc&&!String(state.rows[i][id]??'').trim())continue;const v=values[i][id];if(v===null||v===undefined)throw Error('Há valores inválidos na coluna '+nameOf(id)+'.');xs.push(v);}const result=P.statistics(xs);statMemo.set(id,result);return result;}
function evaluateCalc(calc,values,row){if(calc.stat){const s=statFor(calc.source,values),x=values[row][calc.source];if(x===null||x===undefined)return null;if(['std','sem'].includes(calc.stat)&&s.n<2)throw Error('Desvio amostral exige pelo menos duas medidas.');return ({mean:s.mean,std:s.s,sem:s.sem,deviation:x-s.mean,absdeviation:Math.abs(x-s.mean)})[calc.stat];}
 const vals={},unc={};for(const id of calc.inputs){const v=values[row][id];if(v===null||v===undefined)throw Error('Falta um valor válido em '+nameOf(id)+'.');vals[id]=v;if(calc.output==='uncertainty'){const uid=calc.unc[id];unc[id]=uid==='zero'?0:values[row][uid];if(unc[id]===null||unc[id]===undefined)throw Error('Falta uma incerteza válida para '+nameOf(id)+'.');}}
 return calc.output==='uncertainty'?P.propagate(calc.tree,vals,unc).uncertainty:P.evaluate(calc.tree,vals).v;}
function recalc(){statMemo.clear();cache=state.rows.map(()=>({}));errors=state.rows.map(()=>({}));for(const c of state.cols){for(let i=0;i<state.rows.length;i++){try{cache[i][c.id]=c.calc?evaluateCalc(c.calc,cache,i):(String(state.rows[i][c.id]??'').trim()?P.number(state.rows[i][c.id]):null);}catch(e){cache[i][c.id]=null;errors[i][c.id]=e.message;}}}lastStats=null;const recent=state.cols.filter(c=>c.calc?.stat).at(-1);if(recent){try{lastStats=statFor(recent.calc.source,cache);}catch{}}}
function render(){recalc();$('count').textContent=state.rows.length+' linhas · '+state.cols.length+' colunas';$('table').querySelector('thead').innerHTML='<tr><th>#</th>'+state.cols.map(c=>'<th class="'+(c.calc?'calculated':'')+'"><div class="origin">'+(c.calc?'Calculada':'Original')+'</div><div class="col-top"><input aria-label="Nome da coluna '+esc(c.name)+'" data-name="'+c.id+'" value="'+esc(c.name)+'" maxlength="50"><button class="delete" data-delete="'+c.id+'" aria-label="Excluir coluna '+esc(c.name)+'">×</button></div><input class="unit" data-unit="'+c.id+'" aria-label="Unidade de '+esc(c.name)+'" value="'+esc(c.unit)+'" placeholder="Unidade" maxlength="24"></th>').join('')+'<th></th></tr>';
 $('table').querySelector('tbody').innerHTML=state.rows.map((r,i)=>'<tr><td>'+(i+1)+'</td>'+state.cols.map(c=>{const e=errors[i][c.id];return c.calc?'<td class="output '+(e?'invalid':'')+'" title="'+esc(e||('Precisão completa: '+cache[i][c.id]))+'">'+(e?'Erro':fmt(cache[i][c.id]))+'</td>':'<td><input inputmode="decimal" data-row="'+i+'" data-col="'+c.id+'" aria-label="'+esc(c.name)+', linha '+(i+1)+'" aria-invalid="'+Boolean(e)+'" title="'+esc(e||'')+'" value="'+esc(r[c.id]??'')+'"></td>';}).join('')+'<td><button class="delete" data-row-delete="'+i+'" aria-label="Excluir linha '+(i+1)+'">×</button></td></tr>').join('');
 $('undo').disabled=!state.cols.some(c=>c.calc);$('redo').disabled=!redo.length;
 $('history').innerHTML=state.cols.filter(c=>c.calc).map(c=>'<li><strong>'+esc(c.name)+'</strong> = '+esc(c.calc.label)+(c.calc.output==='uncertainty'?' · incerteza propagada':'')+(c.unit?' ['+esc(c.unit)+']':'')+'</li>').join('');
 $('stats').innerHTML=lastStats?Object.entries({Medidas:lastStats.n,Média:lastStats.mean,Mínimo:lastStats.min,Máximo:lastStats.max,'Desvio amostral':lastStats.s,'Desvio da média':lastStats.sem}).map(([k,v])=>'<div class="stat">'+k+'<strong>'+(v===null?'—':k==='Medidas'?v:fmt(v))+'</strong></div>').join(''):'';
 const count=errors.reduce((n,r)=>n+Object.keys(r).length,0);if(count)status(count+' célula(s) inválida(s). Corrija as medidas; exportação bloqueada até a correção.',true);
}
function selectColumns(id,selected,zero=false){return '<select id="'+id+'">'+(zero?'<option value="">Selecione a incerteza</option><option value="zero">0 (exata)</option>':'')+state.cols.map(c=>'<option value="'+c.id+'" '+(c.id===selected?'selected':'')+'>'+esc(c.name)+(c.unit?' ['+esc(c.unit)+']':'')+'</option>').join('')+'</select>';}
function definition(){return defs.find(d=>d[0]===$('formula').value);}
function prepare(){const previous=Object.create(null);if(prepared)prepared.vars.forEach((v,i)=>previous[v]={id:$('map-'+i)?.value,u:$('unc-'+i)?.value});const d=definition(),custom=d[0]==='custom';let expression=custom?$('expression').value.trim():d[3];if(custom&&expression.includes('=')){const a=expression.split('=');if(a.length!==2)throw Error('Use uma única igualdade.');$('result-name').value=a[0].trim();expression=a[1];}
 let tree=null,vars=['x'];if(d[3]!==null){tree=P.parse(expression,state.cols.map(c=>c.name));vars=P.variables(tree).filter(v=>!Object.hasOwn(d[5]||{},v));}
 prepared={tree,vars,expression,stat:d[3]===null?d[0]:null,params:d[5]||{},custom};
 $('mappings').innerHTML=vars.map((v,i)=>'<label>'+esc(v)+' → coluna'+selectColumns('map-'+i,(state.cols.some(c=>c.id===previous[v]?.id)?previous[v].id:null)||state.cols.find(c=>c.name===v)?.id||state.cols[Math.min(i,state.cols.length-1)]?.id)+'</label>').join('');
 $('parameters').innerHTML=Object.entries(prepared.params).map(([k,v])=>'<label>Expoente '+k+' (exato)<input id="param-'+k+'" value="'+v+'" inputmode="decimal"></label>').join('');
 $('prop-box').hidden=Boolean(prepared.stat)||['absolute','relative','percent'].includes(d[0]);if($('prop-box').hidden)$('propagate').checked=false;
 updateUncertainties();vars.forEach((v,i)=>{if(previous[v]?.id===$('map-'+i)?.value&&previous[v]?.u&&($('unc-'+i)?.querySelector('option[value="'+previous[v].u+'"]')))$('unc-'+i).value=previous[v].u;});$('equation').textContent=custom?expression:d[4];
}
function updateUncertainties(){if(!prepared)return;$('uncertainties').hidden=!$('propagate').checked;$('u-name-box').hidden=!$('propagate').checked;$('uncertainties').innerHTML=prepared.vars.map((v,i)=>{const id=$('map-'+i)?.value,base=nameOf(id);const found=state.cols.find(c=>c.name.toLowerCase()==='v'+base.toLowerCase());return '<label>v('+esc(v)+') → coluna'+selectColumns('unc-'+i,found?.id||'',true)+'</label>';}).join('');}
function choose(){prepared=null;$('result-unit').value='';const d=definition();$('custom-box').hidden=d[0]!=='custom';$('formula-help').textContent=d[3]===null?'Estatística de uma coluna: células vazias são ignoradas; valores inválidos são sinalizados. Média e desvios globais são repetidos nas linhas preenchidas.':d[1]==='Linearização'?'Para logaritmos, use uma razão adimensional (por exemplo, t / 1 s). A unidade não é convertida automaticamente.':'Associe cada variável a uma coluna. Os expoentes informados são tratados como exatos.';
 $('result-name').value=({mean:'média',std:'s',sem:'σmédia',deviation:'desvio',absdeviation:'desvio absoluto',sumsquares:'D²',square:'x²',cube:'x³',sqrt:'√x',inverse:'1/x',ln:'ln(x)',log10:'log10(x)',percent:'E%',relative:'Er',absolute:'Ea'})[d[0]]||'resultado';$('uncertainty-name').value='v'+$('result-name').value;prepare();}
function ancestors(id){const c=state.cols.find(c=>c.id===id);if(!c?.calc)return new Set([id]);const ids=c.calc.stat?[c.calc.source]:[...c.calc.inputs,...Object.values(c.calc.unc||{}).filter(x=>x!=='zero')];return new Set(ids.flatMap(i=>[...ancestors(i)]));}
function calculate(){if(!state.rows.length)throw Error('Adicione pelo menos uma linha.');if(definition()[0]==='custom'){const expr=$('expression').value.trim().split('=').at(-1).trim();if(expr!==prepared?.expression){prepare();throw Error('Expressão atualizada. Confira as colunas e incertezas identificadas e clique em Calcular novamente.');}}
 if(!prepared)throw Error('Escolha uma fórmula.');const name=$('result-name').value.trim(),unit=$('result-unit').value.trim();const wantU=$('propagate').checked&&!$('prop-box').hidden;const onlyU=wantU&&$('output-mode').value==='uncertainty';if(!onlyU)validateName(name);let un=$('uncertainty-name').value.trim();if(wantU){validateName(un);if(!onlyU&&un===name)throw Error('Use nomes diferentes para valor e incerteza.');}
 recalc();let calc;if(prepared.stat){const source=$('map-0').value;const s=statFor(source,cache);if(['std','sem'].includes(prepared.stat)&&s.n<2)throw Error('Desvio amostral exige pelo menos duas medidas.');calc={stat:prepared.stat,source,label:definition()[2]+' de '+nameOf(source)};}
 else{const maps=Object.create(null),unc=Object.create(null);prepared.vars.forEach((v,i)=>{const id=$('map-'+i).value;if(!id)throw Error('Selecione a coluna de '+v);maps[v]=id;if(wantU){const u=$('unc-'+i).value;if(!u)throw Error('Selecione a incerteza de '+v);if(unc[id]&&unc[id]!==u)throw Error('A mesma grandeza deve usar a mesma coluna de incerteza.');unc[id]=u;}});
 const params={};for(const k of Object.keys(prepared.params))params[k]=P.number($('param-'+k).value);
 function bind(t){if(t.type==='var')return Object.hasOwn(params,t.name)?{type:'num',value:params[t.name]}:{type:'var',name:maps[t.name]};return {...t,...(t.a?{a:bind(t.a)}:{}),...(t.b?{b:bind(t.b)}:{})};}
 const inputs=[...new Set(Object.values(maps))];if(wantU){for(let i=0;i<inputs.length;i++)for(let j=i+1;j<inputs.length;j++){const a=ancestors(inputs[i]),b=ancestors(inputs[j]);if([...a].some(x=>b.has(x)))throw Error('Essas colunas compartilham medidas e podem estar correlacionadas. Para propagar, escreva a fórmula diretamente com as grandezas originais independentes.');}}
 calc={tree:bind(prepared.tree),inputs,unc,output:'value',label:prepared.expression+'; '+Object.entries(maps).map(([v,id])=>v+' = '+nameOf(id)).join(', ')+(Object.keys(params).length?'; '+Object.entries(params).map(([k,v])=>k+' = '+v).join(', '):'')};}
 const candidates=onlyU?[]:[{id:'c'+state.next++,name,unit,calc}];if(wantU)candidates.push({id:'c'+state.next++,name:un,unit,calc:{...calc,output:'uncertainty'}});
 if(state.cols.length+candidates.length>100)throw Error('Limite de 100 colunas.');
 for(const c of candidates)for(let i=0;i<state.rows.length;i++){try{evaluateCalc(c.calc,cache,i);}catch(e){throw Error('Linha '+(i+1)+': '+e.message+' Nenhuma coluna foi criada.');}}
 state.cols.push(...candidates);redo=[];dirty=true;render();status(candidates.map(c=>c.name).join(' e ')+' criada(s). Resultados calculados sem arredondamento intermediário.');prepare();}
function imported(text,header=true){const matrix=P.parseDelimited(text),heads=header?matrix.shift():matrix[0].map((_,i)=>'coluna'+(i+1));if(!heads.length||!matrix.length)throw Error('Informe cabeçalho e pelo menos uma linha.');const cols=heads.map((h,i)=>{const m=h.trim().match(/^(.*?)\s*\[([^\]]*)\]$/);return {id:'c'+(i+1),name:m?m[1].trim():h.trim(),unit:m?m[2]:''};});if(cols.some(c=>!c.name)||new Set(cols.map(c=>c.name)).size!==cols.length)throw Error('Cabeçalhos devem ter nomes únicos e preenchidos.');const old=state;state={cols:[],rows:[],next:1};try{for(const c of cols)validateName(c.name);state.cols=cols;for(const r of matrix){if(r.length!==cols.length)throw Error('Todas as linhas devem ter '+cols.length+' células.');const row={};cols.forEach((c,i)=>{if(r[i].trim())P.number(r[i]);row[c.id]=r[i];});state.rows.push(row);}state.next=cols.length+1;}catch(e){state=old;throw e;}redo=[];dirty=true;render();choose();status('Tabela importada. As colunas são consideradas dados originais.');}
function exportData(){recalc();if(errors.some(e=>Object.keys(e).length))throw Error('Corrija as células inválidas antes de exportar.');const rounded=$('export-rounded').checked;return {headers:state.cols.map(c=>c.name+(c.unit?' ['+c.unit+']':'')),rows:cache.map(r=>state.cols.map(c=>r[c.id]===null?'':rounded?P.number(fmt(r[c.id])):r[c.id]))};}
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function refresh(){dirty=true;redo=[];render();prepare();}
blank();for(const group of [...new Set(defs.map(d=>d[1]))]){const el=document.createElement('optgroup');el.label=group;for(const d of defs.filter(d=>d[1]===group)){const o=document.createElement('option');o.value=d[0];o.textContent=d[2];el.append(o);}$('formula').append(el);} $('formula').value='sumsquares';render();choose();
$('formula').onchange=guard(choose);$('prepare').onclick=guard(prepare);$('propagate').onchange=updateUncertainties;$('mappings').onchange=updateUncertainties;$('result-name').oninput=()=>{$('uncertainty-name').value='v'+$('result-name').value;};$('calculate').onclick=guard(calculate);
$('table').onchange=guard(e=>{const t=e.target;if(t.dataset.col){state.rows[+t.dataset.row][t.dataset.col]=t.value;dirty=true;redo=[];render();status('Medida atualizada. As colunas calculadas foram recalculadas.');const count=errors.reduce((n,r)=>n+Object.keys(r).length,0);if(count)status('Há '+count+' célula(s) inválida(s). Consulte os campos marcados.',true);}if(t.dataset.name){const c=state.cols.find(c=>c.id===t.dataset.name);try{validateName(t.value.trim(),c.id);c.name=t.value.trim();refresh();}catch(e){t.value=c.name;throw e;}}if(t.dataset.unit){state.cols.find(c=>c.id===t.dataset.unit).unit=t.value.trim();refresh();}});
$('table').onclick=guard(e=>{const t=e.target;if(t.dataset.rowDelete!==undefined){const i=+t.dataset.rowDelete;if(confirm('Excluir a linha '+(i+1)+' e recalcular os resultados?')){state.rows.splice(i,1);refresh();}}if(t.dataset.delete){const id=t.dataset.delete;const depend=state.cols.some(c=>c.calc&&(c.calc.source===id||c.calc.inputs?.includes(id)||Object.values(c.calc.unc||{}).includes(id)));if(depend)throw Error('Outra coluna depende desta. Desfaça os cálculos dependentes primeiro.');if(state.cols.length===1)throw Error('Mantenha pelo menos uma coluna.');if(confirm('Excluir a coluna '+nameOf(id)+'?')){state.cols=state.cols.filter(c=>c.id!==id);state.rows.forEach(r=>delete r[id]);refresh();}}});
$('table').onpaste=guard(e=>{const t=e.target;if(!t.dataset.col)return;const text=e.clipboardData.getData('text');if(!/[\t\n;]/.test(text))return;e.preventDefault();const matrix=P.parseDelimited(text);const start=state.cols.findIndex(c=>c.id===t.dataset.col),row=+t.dataset.row;const width=Math.max(...matrix.map(r=>r.length));if(start+width>state.cols.length)throw Error('Adicione as colunas necessárias antes de colar.');if(state.cols.slice(start,start+width).some(c=>c.calc))throw Error('A colagem não pode sobrescrever colunas calculadas.');if(row+matrix.length>10000)throw Error('Limite de 10.000 linhas.');for(const r of matrix)for(const v of r)if(v.trim())P.number(v);if(!confirm('Colar '+matrix.length+' linha(s) a partir da célula selecionada? Os valores nessa região serão substituídos.'))return;while(state.rows.length<row+matrix.length)state.rows.push({});matrix.forEach((r,i)=>r.forEach((v,j)=>state.rows[row+i][state.cols[start+j].id]=v));refresh();status('Dados colados e resultados recalculados.');});
$('add-row').onclick=guard(()=>{if(state.rows.length>=10000)throw Error('Limite de 10.000 linhas.');state.rows.push({});refresh();});$('add-col').onclick=guard(()=>{if(state.cols.length>=100)throw Error('Limite de 100 colunas.');const name=prompt('Nome da nova coluna:','medida');if(name===null)return;newCol(name.trim());refresh();});
$('clear').onclick=()=>{if(replaceAllowed()){blank();dirty=false;render();choose();status('Tabela limpa.');}};$('example').onclick=()=>{if(!replaceAllowed())return;blank();state.rows=[[12.4,.1,8.3,.1],[12.6,.1,8.1,.1],[12.5,.1,8.2,.1]].map(a=>Object.fromEntries(a.map((v,i)=>[state.cols[i].id,String(v).replace('.',',')])));dirty=true;$('formula').value='sumsquares';render();choose();$('map-0').value=state.cols[0].id;$('map-1').value=state.cols[2].id;$('result-unit').value='mm²';$('propagate').checked=true;updateUncertainties();status('Exemplo: D² = d1² + d2². Calcule o valor e sua incerteza.');};
$('undo').onclick=()=>{const index=state.cols.findLastIndex(c=>c.calc);if(index<0)return;redo.push({col:state.cols[index],index});state.cols.splice(index,1);dirty=true;render();prepare();status('Última coluna calculada removida. Medidas originais preservadas.');};$('redo').onclick=guard(()=>{const item=redo.pop();if(!item)return;validateName(item.col.name);state.cols.splice(item.index,0,item.col);dirty=true;render();prepare();status('Coluna restaurada e recalculada.');});
$('format').onchange=render;$('digits').onchange=render;$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const file=$('file').files[0];if(!file)return;if(file.size>5000000)throw Error('Arquivo maior que 5 MB.');const text=await file.text();if(replaceAllowed())imported(text);}catch(e){status(e.message,true);}finally{$('file').value='';}};$('paste-load').onclick=guard(()=>{if(replaceAllowed())imported($('paste').value);});
$('csv').onclick=guard(()=>{const d=exportData();download('\uFEFF'+P.delimited(d.headers,d.rows.map(r=>r.map(v=>typeof v==='number'?String(v).replace('.',','):v))),'tabela-fisica.csv','text/csv;charset=utf-8');status('CSV exportado.');});$('xlsx').onclick=guard(()=>{const d=exportData();download(makeXLSX(d.headers,d.rows),'tabela-fisica.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');status('XLSX exportado com células numéricas.');});
$('copy').onclick=async()=>{try{const d=exportData(),text=P.delimited(d.headers,d.rows.map(r=>r.map(v=>typeof v==='number'?String(v).replace('.',','):v)),'\t');await navigator.clipboard.writeText(text);status('Tabela copiada. Cole na sua planilha.');}catch(e){status('Não foi possível copiar: '+e.message+' Use a exportação CSV.',true);}};
$('save-session').onclick=guard(()=>{download(JSON.stringify({version:1,state},null,2),'sessao-fisica.json','application/json');dirty=false;status('Sessão salva com medidas e fórmulas.');});$('load-session').onclick=()=>$('session-file').click();
$('session-file').onchange=async()=>{try{const f=$('session-file').files[0];if(!f)return;if(f.size>5000000)throw Error('Arquivo maior que 5 MB.');const data=JSON.parse(await f.text());validateSession(data);if(!replaceAllowed())return;state=data.state;redo=[];dirty=true;render();choose();status('Sessão restaurada. Resultados recalculados a partir das medidas.');}catch(e){status('Sessão inválida: '+e.message,true);}finally{$('session-file').value='';}};
function validateSession(d){if(d?.version!==1||!d.state||!Array.isArray(d.state.cols)||!Array.isArray(d.state.rows))throw Error('Formato desconhecido.');const s=d.state;if(!s.cols.length||s.cols.length>100||s.rows.length>10000||!Number.isSafeInteger(s.next)||s.next<1)throw Error('Limites da tabela inválidos.');const ids=new Set(),names=new Set();let max=0;function checkTree(t,depth=0){if(!t||depth>128)throw Error('Fórmula inválida.');if(t.type==='num'){P.number(t.value);return;}if(t.type==='var'){if(!ids.has(t.name))throw Error('Variável ausente.');return;}if(t.type==='op'&&['+','-','*','/','^'].includes(t.op)){checkTree(t.a,depth+1);checkTree(t.b,depth+1);return;}if(t.type==='unary'&&['+','-'].includes(t.op)){checkTree(t.a,depth+1);return;}if(t.type==='fn'&&['sqrt','ln','log10','abs','exp','sin','cos'].includes(t.name)){checkTree(t.a,depth+1);return;}throw Error('Operação inválida.');}
 for(const c of s.cols){if(!/^c\d+$/.test(c.id)||ids.has(c.id)||typeof c.name!=='string'||!c.name.trim()||c.name.length>50||names.has(c.name)||typeof c.unit!=='string'||c.unit.length>24)throw Error('Coluna inválida.');if(c.calc){const k=c.calc;if(typeof k.label!=='string'||k.label.length>3000)throw Error('Descrição inválida.');if(k.stat){if(!['mean','deviation','absdeviation','std','sem'].includes(k.stat)||!ids.has(k.source))throw Error('Estatística inválida.');}else{if(!['value','uncertainty'].includes(k.output)||!Array.isArray(k.inputs)||k.inputs.some(x=>!ids.has(x)))throw Error('Dependência inválida.');checkTree(k.tree);if(JSON.stringify([...P.variables(k.tree)].sort())!==JSON.stringify([...new Set(k.inputs)].sort()))throw Error('Variáveis inconsistentes.');if(k.output==='uncertainty'&&(!k.unc||k.inputs.some(id=>!ids.has(k.unc[id])&&k.unc[id]!=='zero')))throw Error('Incerteza inválida.');}}ids.add(c.id);names.add(c.name);max=Math.max(max,Number(c.id.slice(1)));}if(s.next<=max)throw Error('Identificadores inválidos.');for(const r of s.rows){if(!r||typeof r!=='object'||Array.isArray(r)||Object.keys(r).some(k=>!ids.has(k))||Object.values(r).some(v=>typeof v!=='string'&&typeof v!=='number'))throw Error('Linha inválida.');}}
window.addEventListener('beforeunload',e=>{if(dirty&&hasData()){e.preventDefault();e.returnValue='';}});
