const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('./engine.js');
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10*Math.max(1,Math.abs(b)),`${a} != ${b}`);
test('example D² and propagation',()=>{const r=P.propagate(P.parse('d1²+d2²'),{d1:12.4,d2:8.3},{d1:.1,d2:.1});near(r.value,222.65);near(r.uncertainty,Math.hypot(2.48,1.66));});
test('sample statistics',()=>{const r=P.statistics([1,2,3]);near(r.mean,2);near(r.s,1);near(r.sem,1/Math.sqrt(3));assert.equal(P.statistics([3]).s,null);});
test('decimal comma and scientific notation',()=>{near(P.number('1,2e-3'),.0012);assert.throws(()=>P.number('1,234.5'));assert.throws(()=>P.number('Infinity'));assert.throws(()=>P.number(''));});
test('safe grammar, precedence and implicit multiplication',()=>{near(P.evaluate(P.parse('-2^2'),{}).v,-4);near(P.evaluate(P.parse('2^3^2'),{}).v,512);near(P.evaluate(P.parse('πD²h/4',['D','h']),{D:2,h:3}).v,3*Math.PI);near(P.evaluate(P.parse('[D²]*h'),{'D²':4,h:3}).v,12);for(const e of ['alert(1)','x.constructor','x=1','(()=>1)()','1;2','[x'] )assert.throws(()=>P.evaluate(P.parse(e),{x:1}));});
test('analytic derivatives and zeros',()=>{near(P.propagate(P.parse('x*y'),{x:0,y:3},{x:.1,y:.2}).uncertainty,.3);near(P.propagate(P.parse('x/y'),{x:0,y:3},{x:.1,y:.2}).uncertainty,.1/3);near(P.propagate(P.parse('ln(x)'),{x:2},{x:.1}).uncertainty,.05);near(P.propagate(P.parse('x-x'),{x:2},{x:.1}).uncertainty,0);near(P.propagate(P.parse('x+x'),{x:2},{x:.1}).uncertainty,.2);near(P.propagate(P.parse('x^2'),{x:0},{x:.1}).uncertainty,0);});
test('domain errors and invalid uncertainties',()=>{for(const e of ['1/x','ln(x)'])assert.throws(()=>P.evaluate(P.parse(e),{x:0}));assert.throws(()=>P.propagate(P.parse('sqrt(x)'),{x:0},{x:.1}));assert.throws(()=>P.propagate(P.parse('x^2'),{x:1},{x:-.1}));assert.throws(()=>P.propagate(P.parse('x^2'),{x:1},{}));assert.throws(()=>P.evaluate(P.parse('x^0.5'),{x:-1}));});
test('CSV parsing and escaped headers',()=>{assert.deepEqual(P.parseDelimited('d1;d2\n12,4;8,3'),[['d1','d2'],['12,4','8,3']]);assert.deepEqual(P.parseDelimited('"a","b"\r\n1.2,3.4'),[['a','b'],['1.2','3.4']]);assert.throws(()=>P.parseDelimited('"a;b'));assert.ok(P.delimited(['=1+1'],[[2]]).startsWith('"\'=1+1"'));});
