(function(root){
'use strict';
const P=typeof module!=='undefined'?require('./engine.js'):root.Physics;
const finite=x=>{if(!Number.isFinite(x))throw Error('Resultado fora do intervalo numérico.');return x;};
const uncertainty=x=>{x=P.number(x);if(x<0)throw Error('A incerteza não pode ser negativa.');return x;};
function treatment(values,instrument){const s=P.statistics(values);const u=instrument==null?null:uncertainty(instrument);return {...s,instrument:u,total:s.sem===null||u===null?null:finite(Math.hypot(s.sem,u))};}
function relative(x,u){x=P.number(x);u=uncertainty(u);if(x===0)throw Error('Incerteza relativa indefinida para valor zero.');return finite(u/Math.abs(x));}
function report(x,u){x=P.number(x);u=uncertainty(u);if(u===0)return `${String(x).replace('.',',')} ± 0`;const [mantissa,power]=u.toExponential().split('e');const rounded=finite(Number(Math.round(Number(mantissa))+'e'+power));const place=Math.floor(Math.log10(rounded));const step=10**place;if(!step)throw Error('Incerteza pequena demais para a apresentação decimal.');const scaled=Math.abs(x)/step;const mean=finite(Math.sign(x)*Math.round(scaled+Number.EPSILON*scaled)*step);const exp=Math.abs(mean)>=1e6||rounded<1e-4?Math.floor(Math.log10(Math.max(Math.abs(mean),rounded))):0;const digits=Math.max(0,Math.min(16,exp-place));const a=(mean/10**exp).toFixed(digits).replace('.',','),b=(rounded/10**exp).toFixed(digits).replace('.',',');return exp?`(${a} ± ${b}) × 10^${exp}`:`${a} ± ${b}`;}
const models={
 block:{name:'Volume do paralelepípedo',formula:'a*b*c',display:'V = a · b · c',vars:['a','b','c'],unitPower:3,source:'Apostila, cap. 3, pp. 14–15'},
 cylinder:{name:'Volume do cilindro',formula:'pi*D^2*h/4',display:'V = πD²h / 4',vars:['D','h'],unitPower:3,source:'Relatório 01, equações 6 e 14'},
 washer:{name:'Volume da arruela',formula:'pi*h*(D2^2-D1^2)/4',display:'V = πh(D₂² − D₁²) / 4',vars:['D1','D2','h'],unitPower:3,source:'Relatório 01, equação 7; D₁ interno, D₂ externo'},
 shoulder:{name:'Volume com ressalto e furo',formula:'pi*(h2*(D2^2-D1^2)+h1*(D3^2-D1^2))/4',display:'V = π[h₂(D₂² − D₁²) + h₁(D₃² − D₁²)] / 4',vars:['D1','D2','D3','h1','h2'],unitPower:3,source:'Relatório 01, equações 8–10; furo D₁ compartilhado'},
 cut:{name:'Volume com ressalto, furo e corte',formula:'pi*(h2*(D2^2-D1^2)+h1*(D3^2-D1^2))/4-h1*D3^2/8*(2*asin(L/D3)-sin(2*asin(L/D3)))',display:'V = Vressalto − h₁Asegmento',vars:['D1','D2','D3','h1','h2','L'],unitPower:3,source:'Relatório 01, equações 11–17; L é a corda do corte'},
 sumsquares:{name:'Soma dos quadrados',formula:'x^2+y^2',display:'D² = x² + y²; σD² = √[(2xσx)² + (2yσy)²]',vars:['x','y'],unitPower:2,source:'Aplicação da propagação: apostila, equação 3.1'},
 product:{name:'Produto de grandezas',formula:'x*y',display:'z = xy; σz = √[(yσx)² + (xσy)²]',vars:['x','y'],source:'Aplicação da propagação: apostila, equação 3.1'},
 ratio:{name:'Razão entre grandezas',formula:'x/y',display:'z = x/y; σz = √[(σx/y)² + (xσy/y²)²]',vars:['x','y'],source:'Apostila, exemplo de propagação, p. 27'},
 difference:{name:'Diferença de grandezas',formula:'x-y',display:'z = x − y; σz = √(σx² + σy²)',vars:['x','y'],source:'Aplicação da propagação: apostila, equação 3.1'}
};
function checkModel(name,v){const m=models[name];if(!m)throw Error('Modelo desconhecido.');if(['block','cylinder','washer','shoulder','cut'].includes(name))for(const k of m.vars)if(v[k]<=0)throw Error('Dimensões geométricas devem ser positivas.');if(['washer','shoulder','cut'].includes(name)&&v.D2<=v.D1)throw Error('D₂ deve ser maior que o diâmetro interno D₁.');if(['shoulder','cut'].includes(name)&&v.D3<v.D2)throw Error('D₃ (base) deve ser pelo menos D₂ (ressalto).');if(name==='cut'){if(v.L>=v.D3)throw Error('A corda L deve ser menor que D₃.');if(Math.sqrt(v.D3*v.D3-v.L*v.L)<v.D2)throw Error('Este modelo exige que o corte atinja somente a base, sem cortar o ressalto ou o furo.');}}
function model(name,values,uncertainties){const m=models[name];if(!m)throw Error('Modelo desconhecido.');const v={};for(const k of m.vars)v[k]=P.number(values[k]);checkModel(name,v);const tree=P.parse(m.formula);const r=P.propagate(tree,v,uncertainties);return {...r,relative:r.value===0?null:relative(r.value,r.uncertainty),presentation:report(r.value,r.uncertainty)};}
function transform(kind,x,u,reference=1){x=P.number(x);u=uncertainty(u);reference=P.number(reference);let value,ux;if(kind==='ln'||kind==='log10'){if(reference<=0||x<=0)throw Error('Logaritmo exige medida e referência positivas.');const base=kind==='ln'?1:Math.LN10;value=Math.log(x/reference)/base;ux=u/(Math.abs(x)*base);}else if(kind==='square'){value=x*x;ux=2*Math.abs(x)*u;}else if(kind==='inverse'){if(x===0)throw Error('Inverso indefinido para zero.');value=1/x;ux=u/(x*x);}else throw Error('Transformação desconhecida.');return {value:finite(value),uncertainty:finite(ux)};}
function regression(points){if(points.length<2)throw Error('São necessários pelo menos dois pontos.');const p=points.map(p=>({x:P.number(p.x),y:P.number(p.y),u:uncertainty(p.u)}));if(p.some(p=>p.u===0))throw Error('As incertezas verticais devem ser maiores que zero.');const scale=Math.min(...p.map(p=>p.u)),w=p.map(p=>(scale/p.u)**2),S=w.reduce((a,b)=>a+b,0),x0=p[0].x,y0=p[0].y;const xm=x0+p.reduce((s,p,i)=>s+w[i]*(p.x-x0),0)/S,ym=y0+p.reduce((s,p,i)=>s+w[i]*(p.y-y0),0)/S;const XX=p.reduce((s,p,i)=>s+w[i]*(p.x-xm)**2,0),XY=p.reduce((s,p,i)=>s+w[i]*(p.x-xm)*(p.y-ym),0);if(!(XX>0))throw Error('Os valores de X precisam variar.');const a=finite(XY/XX),b=finite(ym-a*xm),ua=finite(scale/Math.sqrt(XX)),ub=finite(scale*Math.sqrt(1/S+xm*xm/XX));const rows=p.map(p=>{const fit=finite(ym+a*(p.x-xm)),res=finite(p.y-fit),weight=finite(1/(p.u*p.u));return {x:p.x,y:p.y,u:p.u,w:weight,wx:finite(weight*p.x),wy:finite(weight*p.y),wxx:finite(weight*p.x*p.x),wxy:finite(weight*p.x*p.y),fit,res,chi:finite((res/p.u)**2)};});const chi=finite(rows.reduce((s,r)=>s+r.chi,0));return {a,b,ua,ub,covariance:finite(-xm*ua*ua),chi,df:p.length-2,reduced:p.length>2?chi/(p.length-2):null,rows};}
function powerReturn(a,ua,b,ub,yref){a=P.number(a);ua=uncertainty(ua);b=P.number(b);ub=uncertainty(ub);yref=P.number(yref);if(yref<=0)throw Error('A referência de Y deve ser positiva.');const C=finite(yref*Math.exp(b));return {n:a,un:ua,C,uC:finite(C*ub)};}
const API={uncertainty,treatment,relative,report,models,model,transform,regression,powerReturn};root.Lab=API;if(typeof module!=='undefined')module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);
